apiVersion: v2
name: llm-proxy
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.97.0"

dependencies:
  - name: litellm-helm
    version: 1.97.0
    repository: oci://ghcr.io/berriai
    alias: litellm
