apiVersion: v1
kind: Secret
metadata:
  name: runtime-secrets
stringData:
  masterkey: {{ dig "MASTERKEY" "" .Values.env | quote }}
  VSHN_US_AI_API_KEY: {{ dig "VSHN_US_AI_API_KEY" "" .Values.env | quote }}
