apiVersion: v1
kind: Secret
metadata:
  name: runtime-secrets
type: Opaque
data:
{{- range $key, $value := .Values.vars }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
